### ISSUE TITLE
TransformError: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by jakkan** [MagicTheGathering/mtg-sdk-javascript#6] opened 2017-01-15 22:05 UTC
I get the following error when trying to use your project in my react-native application.

> TransformError: /myproject/node_modules/mtgsdk/lib/index.js: Couldn't find preset "es2015" relative to directory /myproject/node_modules_mtgsdk

I'm not sure whether this problem has to do with the SDK or if it a problem on my side with integrating your package into my application.

Thanks for creating and maintaining this project. It looks nice!

**Comment by raineorshine** [comment] 2017-01-15 23:52
Hi! Thanks for reporting. All of the babel transforms are done at compile-time and then committed into source control for into the lib directory. Consuming applications shouldn't be aware of any part of the build process at the point of usage, so I am not sure it it is possible to get that error by just requiring the file. I took another look at the code and I don't see anything obvious. Take a look at lib/index.js and lib/querybuilder.js and you'll see how straightfoward it is. 

Maybe you can do some more troubleshooting to find out where the problem might be coming from? If you can provide steps to reproduce I am also happy to take a look!

**Comment by jakkan** [comment] 2017-01-16 21:18
Thank you for offering to take a closer look! I'll try to find out more, and post again when I have hopefully found a solution.

**Comment by raineorshine** [comment] 2017-02-13 17:18
@jakkan Any progress?

**Comment by raineorshine** [comment] 2018-08-19 16:38
Closing due to inactivity

**Closed by raineorshine** 2018-08-19 16:38 UTC
